version: 2
jobs:
  build:
    docker:
      - image: fpco/stack-build:lts-8.5
    working_directory: /app
    environment:
      CLOUDSDK_CORE_DISABLE_PROMPTS: 1
      # This is not nice. Just want to prepend /opt/google-cloud-sdk/bin to $PATH
      # but this isn't support in CircleCI 2.0 at the moment.
      # This should be built into the base build image anyhow.
      PATH: /opt/google-cloud-sdk/bin:/root/.cabal/bin:/root/.local/bin:/opt/ghc/8.0.2/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    steps:
      - run:
          name: Environment Variables
          command: |
            echo "Hello CircleCI 2.0"
            echo "CIRCLE_BUILD_NUM = ${CIRCLE_BUILD_NUM} (empty for local builds)"
            echo "CIRCLE_BRANCH = ${CIRCLE_BRANCH}"
            echo "CIRCLE_PULL_REQUEST = ${CIRCLE_PULL_REQUEST}"
            circlePullRequestId=${CIRCLE_PULL_REQUEST##*/}
            echo "circlePullRequestId = ${circlePullRequestId}"
            echo "CIRCLE_TAG = ${CIRCLE_TAG}"

      - checkout

      - restore_cache:
          key: stack-work

      - run:
          name: Build
          command: |
            echo PATH=$PATH
            which stack
            stack --version
            stack setup
            stack build

      - save_cache:
          key: stack-work-{{.BuildNum}}
          paths:
            - .stack-work


      - setup_remote_docker

      - run:
          name: Install Docker client
          command: |
            curl -fsSLO https://get.docker.com/builds/Linux/x86_64/docker-17.04.0-ce.tgz && tar --strip-components=1 -xvzf docker-17.04.0-ce.tgz -C /usr/local/bin
            ls

      - run:
          name: Build docker image
          command: |
            stack image container

      - run:
          name: Push image to Docker Hub
          command: |
            docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
            docker push steshaw/scotty-example

      - run:
          name: Install Google Cloud Platform SDK
          command: |
              mkdir -p /opt
              curl -sS https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-153.0.0-linux-x86_64.tar.gz | tar -xzf - -C /opt

      - run:
          name: Configure Google Cloud Platform SDK
          command: |
            set -eu
            GCLOUD_COMPUTE_ZONE=us-central1-b
            GCLOUD_CLUSTER_NAME=k0
            GCLOUD_PROJECT=dev0-166300
            echo $GCLOUD_SERVICE_KEY | base64 --decode >~/gcloud-service-key.json
            gcloud config set core/disable_prompts true
            gcloud components update
            gcloud components install kubectl
            gcloud auth activate-service-account --key-file ~/gcloud-service-key.json
            gcloud config set compute/zone $GCLOUD_COMPUTE_ZONE
            gcloud config set project $GCLOUD_PROJECT
            gcloud config set container/cluster $GCLOUD_CLUSTER_NAME
            gcloud container clusters get-credentials $GCLOUD_CLUSTER_NAME
            kubectl config current-context
            kubectl config get-contexts
            kubectl config get-clusters

      - deploy:
          name: Deploy to GKE
          command: |
            set -eu
            env
            if [[ ${CIRCLE_BRANCH} != master ]]; then
              namespace="staging-${CIRCLE_BRANCH}"
              k8s/apply-namespace ${namespace}
              kubectl --namespace=${namespace} apply -f k8s/
            fi
