version: 2
jobs:
  build:
    docker:
      - image: haskell:8.0.2
    working_directory: /app
    steps:
      - run:
          name: Environment Variables
          command: |
            echo "Hello CircleCI 2.0"
            echo "CIRCLE_BUILD_NUM = ${CIRCLE_BUILD_NUM} (empty for local builds)"
            echo "CIRCLE_BRANCH = ${CIRCLE_BRANCH}"
            echo "CIRCLE_PULL_REQUEST = ${CIRCLE_PULL_REQUEST}"
            circlePullRequestId=${CIRCLE_PULL_REQUEST##*/}
            echo "circlePullRequestId = ${circlePullRequestId}"
            echo "CIRCLE_TAG = ${CIRCLE_TAG}"
      - checkout
      - run:
          name: Build
          command: |
            which stack
            stack --version
            stack build

      - run:
          name: Build docker image
          command: |
            stack image container

      - setup_remote_docker

      # This should go into custom primary image, here's only for the sake of explanation
      - run:
          name: Install Docker client
          command: |
            curl -fsSLO https://get.docker.com/builds/Linux/x86_64/docker-17.04.0-ce.tgz && tar --strip-components=1 -xvzf docker-17.04.0-ce.tgz -C /usr/local/bin
            ls

      - run:
          name: Push image to Docker Hub
          command: |
            docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
            docker push steshaw/scotty-example
