version: 2
jobs:
  build:
    docker:
      - image: ubuntu:14.04
    working_directory: /app
    steps:
      - run: |
          echo "Hello CircleCI 2.0"
          echo "${CIRCLE_BRANCH}"
          echo "${CIRCLE_PULL_REQUEST}"
          echo "${CIRCLE_PULL_REQUEST##*/}"
