#!/usr/bin/env bash

if [[ $# -ne 1 ]]; then
  echo "usage: $0 branch-name"
  exit 2
fi

branch=$1; shift

set -eu

kubectl apply -f - <<!
apiVersion: v1
kind: Namespace
metadata:
  name: staging-${branch}
!
