#!/usr/bin/env bash

if [[ $# -ne 2 ]]; then
  echo "usage: $0 namespace image"
  exit 2
fi

namespace=$1; shift
image=$1; shift

set -eu

kubectl --namespace=${namespace} apply -f - <<!
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: scotty
  name: scotty
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: scotty
    spec:
      containers:
      - args:
        - /usr/local/bin/scotty-example
        image: ${image}
        name: scotty
        ports:
        - containerPort: 3000
        resources: {}
  selector:
    matchLabels:
      run: scotty
!
