apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: github-webhook
  name: github-webhook
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      run: github-webhook
  template:
    metadata:
      labels:
        run: github-webhook
    spec:
      containers:
        - name: github-webhook
          image: steshaw/k8s-staging-teardown
          env:
            - name: WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: webhook
                  key: webhookSecret
