apiVersion: v1
kind: Service
metadata:
  labels:
    run: github-webhook
  name: github-webhook
  namespace: staging
spec:
  ports:
    - port: 80
      targetPort: 3000
  selector:
    run: github-webhook
  type: LoadBalancer
